services:
  - type: web
    name: prject-php-app
    env: docker
    dockerfilePath: Dockerfile
    autoDeploy: true
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
